ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS original_total DECIMAL(10,2),
  ADD COLUMN IF NOT EXISTS discount_total DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS promo_code_id INTEGER,
  ADD COLUMN IF NOT EXISTS promo_code VARCHAR,
  ADD COLUMN IF NOT EXISTS promo_discount DECIMAL(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_breakdown JSONB;